### PR TITLE
Implemented Steiner Tree optimizer for "Skill Highlighted Nodes"

### PR DESCRIPTION
**Pull request by MLanghof**
I'd consider the coding work for #98 done.

There's still the part of writing a decent documentation, but I don't feel like I'll get that done tonight. If you don't want to add that separately later, just leave this open I guess.

Oh right, and the window owner thing. Well, no rush.

### CODE REVIEW

**Comment by EmmittJ** [comment]
If everyone wants to check and see if there is anything missing before merge that would be great
@l0g0sys @SpaceOgre

**Comment by SpaceOgre** [comment]
Looks go to me, I will fix the window owner thing after the merge is done and other than that I think it looks good.

**Comment by MLanghof** [comment]
Ok, code documentation has been pushed to my repo. If you ever wondered how I approached this, or why the number of used nodes in the best solution sometimes goes up, Steiner.cs is the place to look. :)

**Comment by MLanghof** [comment]
Awesome! Now onto the next project...

**Pull request merged**
