### PR TITLE
Added support for multiple iterations to the Tree Generator

### PR DESCRIPTION
**Pull request by brather1ng**
The "Skill Tree Generator" window now has an option where you can select the number of iterations of the algorithm that should be run. The iterations are internally independent and the best solution from all is taken.

Since one iterations only takes a few seconds this felt like an easy improvement if you are willing to wait a few more seconds.

### CODE REVIEW

**Comment by EmmittJ** [comment]
I apologize I haven't gotten to this sooner. I have been fairly busy with class work. I will take a look at this now.

**Comment by brather1ng** [comment]
Don't worry, it's only been a day :)

**Comment by EmmittJ** [comment]
Alright, I am getting an error (`System.NullReferenceException`) in `AdvancedSolver.cs` on `line 326`
1) [load this tree](https://www.pathofexile.com/passive-skill-tree/AAAABAYBAAEJAdwFLQW1BiAISQ3RDkgQkhGWFHUV_Ra_GbQj9iaVKgss4TBxMHwyMjWSN9RDMUX0RwZHfkz_TZJOKlFHVUtW6Fb6WHVbr13yYeJirGNDZK9lTWqMapNsjG9XcFJwVnSgdO11_XfXd-N4DXgZeu99438rhG-E2YnTijiMNo19jb-QG5oTnaqfgqLZpzSpbqxmsNiy3LTFtfK42bk-vG-9Nr6nwBrAnMGgwuzIFNQj1gfYdti92YbawdvU2-fdDd1I4JXjhO0_8uH1b_4KAAAAAA==) 
2) 'Load From Tree' in Skill Tree Generator 
3) Level: 1  
    Add Poinnts: 20  
    Total Points: 20  
    Iteration: 1
4) 'Run'

**Comment by brather1ng** [comment]
Fixed!

**Comment by EmmittJ** [comment]
I haven't found anything else, this is awesome.

**Comment by brather1ng** [comment]
I think you forgot to press merge ;)

**Comment by EmmittJ** [comment]
...yeah

**Comment by brather1ng** [comment]
Huh, since when does GitHub squash commits on merge? I don't really mind it much but it somewhat invalidates your own contributions map because intermediate commits are not shown there.

**Comment by EmmittJ** [comment]
Erm.....I have no idea. I just normally click 'merge', and it does it's thing. I will check to see if there is an option next time...

**Comment by brather1ng** [comment]
Looks like GitHub introduced squashing as an option to merging: https://github.com/blog/2141-squash-your-commits

**Comment by EmmittJ** [comment]
Alright, well I will make sure the next time to double check the merge
method, sorry about that.

**Pull request merged**
