### PR TITLE
Simple Item Filter editor

### PR DESCRIPTION
**Pull request by l0g0sys**
Upstream merge deleted those 2 files for some reason, so just replaced them with raws from Github page.
Should be fixed now. Replaced them from downloaded repo Zip.

### CODE REVIEW

**Comment by brather1ng** [comment]
I think for this to work, you have to merge the revert commit into your branch, revert it and then fix the data lists.

**Comment by l0g0sys** [comment]
It won't :(
Merge with upstream will delete everyhing i did. But i see that now only those 2 files are in pull request.
Oh bow. Don't know how to fix it at all.

**Comment by EmmittJ** [comment]
I can't do much right now. I am on my way to work.

**Comment by EmmittJ** [comment]
Reverting my pr should reinstate your changes then merge this?

**Comment by l0g0sys** [comment]
Don't know. But if you can get code back as it was after merge and just replace those 2 files from revision before it should work.

**Comment by brather1ng** [comment]
Yes, merge with upstream will delete everything because of the revert commit. If you revert that, it'll be fine. So, revert the revert commit and then fix the two files.

Give me moment, I'll fix this.

**Comment by l0g0sys** [comment]
Thx. Can i close thise one? Will you fix those 2 files?

**Comment by brather1ng** [comment]
Yep, I'll just reload those files.

**Comment by brather1ng** [comment]
Should be fixed now. That's a nice bit of Git history this stuff has produced :D

**Comment by EmmittJ** [comment]
My fault really haha

**Comment by l0g0sys** [comment]
Gonna try to merge upstream now :) Hope it wont delete everything again.

**Pull request closed without merging**
