### PR TITLE
Refactoring/drawing

### PR DESCRIPTION
**Pull request by EmmittJ**
Hey everyone,

I have been done doing this for awhile but was busy, so I wanted to clean everything up and get it ready to merge in. Would someone mind going through and sanity checking that nothing is extremely broken. I have redone most of the drawing code so that it is way more efficient. You can now click a node every ~50ms on a normal size tree down from every ~150ms, and on a [full tree](https://www.pathofexile.com/passive-skill-tree/AAAABAYBABpVWp-I7TboYSFFqfoYWK-uUKn6hykB54Zg_7BGaWSjhO9mtu56AQkB3AUtBbUGIAhJDdEOSBCSEZYUdRX9Fr8ZtCP2JpUqCyzhMHEwfDIy_go31EMxRfRHBkd-TP9Nkk4qUUdVS1boVvpYdVuvXfJh4mKsY0Nkr2VNaoxqk2yMb1dwUnBWdKB07XX9d9d343gNeBl6733jfyuEb4TZidOKOIw2jX2Nv5AbmhOdqp-CotmnNKlurGaw2LLctMXYvbjZuT68b702vqfAGsCcwaDC7MgU1CPWB9h2NZLZhtrB29Tb590N3UjgleOE7T_y4fVvtfL-a-HvFE0b-iKvBORD56LqYux7dKcw5K3zbzpSYVKpJ8qQ7g5FfBPJTUb8SyXfOFN10DndEuG2imWnn8tgxEnVvJ_vTnh6v9XDM7TR1ELi1ar48kX-j16LsKsuUxjbIXbuFcjcj8GNgeaBB2MM8lYt1FIVIMS4bmkGohfcd_2iLmwIVvVUR57E_5MhwFHZL8yfowZwlQWplJAN-usrCtZYI9MPq5OV0NDIzFBClcw-z41-dcs93d749vw2PRvIcFG3MG6qbbRzs-UZYEFXl0Cg3UY51Dqtew1vO-dUcmzYYHLDtz7o1qOKBx4ajd2oOrMNjS2Dwo5_xipbkAp5aKTC1orl5rakns1nWA48Mn7FU5OokGy9gfzFLEYe8MGCLiO2LHbndPHksZLQxILmiF4TGekJuxiRhtG1SFO7WhrIDKZ_7UGoojrhTePd5_Tm02-mjYbOt3XBSUscy_XLvRSppcve5QMnLOnV-F9qz-lSsiSLj2Dxittupr4RL7CSsw4xs9nGp59OnwiJh2ozeJLzAx7gn28nbWytM4_6749TNfljvebNmOpiZ2ekeOtjVYXP3XZv6FpkhKgH8Gu0OGNwEdXAv2OndvdvhG06zwok_WxG1y2rC4haIuqxs5UuWyZLeId2FfYwW_ihfll59sEEP_xVtUKOnMTelunVYJEsp4qz3DIRGulG73qBrJeX2o0JM_ajPL23ttgL-vGzAxQJSsgLwSFgRrdv8kGHg8zN6ud0mybrFKKjJ6mTJ8HFgl7ynNIh378UcZkrtxeTmS0wpBkppYrwg70hVScLdoJEniyFwdimV93jdU7BM_4dMbD46xuq8kEA7kTSVw3rjoJTN4HDOqBD-u-X0Fha8NXsGOv1V9gylLkden-a8RXw5zpeRR9BBWaaauywGddcQN9vlLhU_nvX034brZ8nwdUMc7EwLVV-sCaIBqBngBXn-_VewASHqZURgTH6_xzopBNQ_94yCUkPzAagQmqVeK5noH_7OkLjn2J5rJebLY6_QzZfP-hmRA3iQ7cimAp5OUrEeGlXVEh4c2txsOcKAbwzkodBq9LRNr6KbAsvnVpSiq8yGBNtPycPxMGLnL6gn_noPC0yAdsaBfnB81F074hciohCUuxul2oe20_ZfHjrFexc-bue7deJ4BmKXzks-9w9g7ZLCtlhlmzDCWSqTm3BBzGeLL_8ZPPdEcJl8Lvtm7VkUoDh3L3qGBDwggcqTaPn85vxrJP8Lgjk6yo4E4NXh46KUilJUXC7ZJ0b4H8CXWgGIwBedK6MC4fLVL0Dh3sUSO59dSSdBLEWqrUIlWbaZOn-2FT5vY-ZDPe_AJoXPeJ_40p9AAaVhxQgG0X2SBo-CLHI8I7pCNSVIH7i9q7Grhg8BTwi9KEvCpvOqEMTtBolP-IsytPJPRbzqJqQEVMx26fPMjt8gUENH2h0gseDX7IZEHuXBoIeGoH5Nx3Zajv3vhzn4MP3MmRadqzmWMgj-wkZLooiB3Wtjak0hVKRzrmTm4alxNd-NdYV10qaaGWd2cGjX7CExU4y4l7nD1Hm8loXPn1bAhEpLuNWDo6ArlXg2RPyHRn-puDKqeHbGY7bVbl8p5sV7f66Ylo90XGhrj6PTwV9H1vE9jJOrK-TkJKADF8x-_IvxFgdg-8OxtiMz3y4axdzbaaZigYtHxDMC2H9ML0nbRl90tsLm4306R2-KPp7w7QMv5cmPJtdguQGdwlYWW24yjXvPCjaYtP7xKLPer46-TMUsNfPQ1QlvEfio-982TiWz36THwWT9trUjycgwKabamEG6wlqNpwyYxdFCoauogQjX-JhykqsRxfhFI60L3dTgTq01EWWRbkvb7JwGwFb9LiToaTtgwLQV8l1npaLu-PfmNlbvYJnmxFQffXEFa-nG5eX9C2LHKcY15tYCPQ9_JM6UEdYY4iP_oe86vD5TLMdT8UoK7avbGoEGFZ9GFSuga8ILjaJM4eYrUZx6rryHkwt8pe-vKEi0_xfmJXIOu0TbJSgqH2n1GHr9Uvn6pphSbH0cSftcqmSfVSCIuJEikkTGo-LT7fZOQ7Wvn6a9MZWY4hbUUwwd2-eJvjAdiE0OzsDAGBz6yyEdypTYpX-yHmhHNwNfDeDzxXVuV1J5FEbJVcrQXQ1ucWKPQ8czmjyUlMfx1OlQkuXlcBU0B8IZyBua9sa5HsgBAdFfq6ziuT2W4xGa9lqpUT77IrfirjQgwlnvQPusHfhiDQKEQ8XVLM_9PjcIychidgGSdhNWpHHynpTwQCv68JzVakGDoCKrKo9PqQ5KCoJltUunwGcpLALbwgZhln-8bMTTKyYQT-exXxLPO_igFRi8B98Do8ai5nr7hT2puskm55XJSeXeUuu_rPcc6crfLsGOStQQ2M9Xyt4sZCFxVfhakPv6xW4UDAfAuvk-JOD2w5cQZab7Fm8_9M0jm03O-MsnOkC2jpgQzsN215Htx2qN2Z-r448T1aiQJhv_gloWGqsyUQB0XNwl7TUfHYrWfPlzzLRmuDo1dHkhxOWdPfXIJw6WEtXdFXxbN-ylIe2hhhdTDKnCKIAp1WFMrlvfIOGOyym9012f3uMgFY62Hfl-6oNzZrPLajfvvllMjTIW4P3NsVfKtD1VcZq-gVCTwQRLRBYVa79YIooSbKxBW49hgL-SY0ZtYVWSh7f15ZyD77uHpTtRJ-IagEJ9ho4nz46nUVHRZ2boY2CdwfMvIRI2t2drsDjIbA22Ngkj0btIK3xIzEVUASzW6C-gOw4p5QBkZDWJy9-4ITET30yiVfi8wb-VHFN21nk7CHDlQSWMoPzi3qHZXYRQ8iOvq-bRKtkCQLjA5ZV1eAS71CeoWaer7fhc9kLlG9xhT9zvJpKLvbnkFUt0lKvtQRTUkjnU9SqxEQEXGsabOWLhW0090kbVkgdFIKb7HSFeylPXl1RYLfWRKFOrgFvUfsTcQN18xFXKZLB-tKPphZA4vcHpdsCOyi3MRhq2V_BtCKBWOXMt5o7KphmVHrmbOdBctWLznDAZohArUq7TWus5CKvjfnb98GFYBCXw2026Rvx1YGXhSqNEmmOZFeUiWuePGu30f3tPBcvrhKxNl6lzRZFjpErsUJG19-wFm-CEIV9eC_zCXjOhQ6MdjlS3YwtfcMTKhPVdZ_f-oA8BWP9CaDJZ6ellFzZ_KasZ_zdXzdHaf5-x025JKoYZSTYLpTsVRcc96YksGTn2rlYrh8Y-4tYdzmKMJfjanzlUWzTGzQgWAdaK-98kwe5Q8xmCaqQM9Wm-d0TzHF5tvqApFXWNDFfBPnIIiaj8kqYwJrx_ouMT_NgZezL), it takes around ~1.5 seconds for the application to respond rather than ~4 seconds. This gain was mainly from reducing the number of redraws the code is doing and limiting down how many times a node was drawn. 

The commits may not show exactly what has been changed since I did a lot of rewriting but all of the old functionality is there and has been broken done a bit more. One of the biggest things that helped with this rewrite is the fact that @brather1ng wrote up an `ObservableSet` class which functions like a `HashSet` with notifications. This means that there is no manual calling of the draw code outside of initialization.

### CODE REVIEW

**Comment by brather1ng** [comment]
Most of it looks great! I noticed a few things:

Ascendancy classes go away until "Show All Ascendancy Classes" is rechecked (persists through restarts) when the root node is unskilled (make sure "Show All Ascendancy Classes" is checked, load the full tree you linked, unskill "Assassin"). The Reset button and a few other cases also makes these go away.

Some debug messages are left over, I noticed timers when skilling nodes like "00:00:00.0640488".

Having "Show All Ascendancy Classes" enabled (and them always being visible) leads to noticeable delays, even with only a few nodes skilled. In this case, the timer is printed when un-/skilling arbitrary nodes and is around 00.0656398. If it is disabled, the timer is only printed when un-/skilling ascendancy nodes and is around 00.0030040 (which is around 20 times less, maybe it does something for every ascendancy class?).

**Comment by EmmittJ** [comment]
Alright, these issues should be fixed.

**Comment by brather1ng** [comment]
Yes, those issues are fixed.

Noticed something else:

- Nothing major: If you click to hide your ascendancy class thing, the show/hide button is invisible until the cursor is moved.
- The skilled ascendancy nodes are somethimes visible when the class background ist not. Reproduction: disable "Show All Ascendancy Classes", load the full tree, hide the ascendancy class, click "Load Tree" again. This also happens when "Show All Ascendancy Classes" is enabled, the tree is loaded, it is disabled and the tree is loaded again (with the nodes being shown where they are with it enabled, not where they should be).

**Comment by EmmittJ** [comment]
These issues should now be fixed

**Comment by brather1ng** [comment]
Yep, looks good to me. I'll go ahead and merge this.

**Pull request merged**
