### PR TITLE
Fix dialog window focus

### PR DESCRIPTION
**Pull request by yazilliclick**
Fixes issues with dialogs not returning to focus when app is switched to and also showing up in alt+tab list separate from the main program.

### CODE REVIEW

**Comment by EmmittJ** [comment]
Will look at this when I get home.

**Comment by SpaceOgre** [comment]
Nice work.
Should add this to the update window as well :)

**Comment by yazilliclick** [comment]
Thanks.  Made the same changes to all the message dialogs called from the main window.

**Comment by SpaceOgre** [comment]
Looks good so will merge it now :)

**Pull request merged**
