### PR TITLE
Removed submodules.

### PR DESCRIPTION
**Pull request by l0g0sys**
Move 3rd party RangeTree and WpfRangeControls components to Contrib folder.
Fixed TestCharacterSheet unit test to pass.

### CODE REVIEW

**Comment by l0g0sys** [comment]
Simple as that. dist-release working again.

**Comment by MLanghof** [comment]
> Fixed TestCharacterSheet unit test to pass.

Did you simply comment out all checks? In that case, shouldn't you rather comment out the entire test (so it doesn't show "Test passed" when there was nothing being tested)?

**Comment by l0g0sys** [comment]
Didn't have time to read everything again about life cycle of Unit 
Tests. I implemented those tests like ages ago, so I've chosen most time 
efficient solution.

And I'd like to get that basic test working again in timeline of few days.

**Comment by l0g0sys** [comment]
More important part is the sub-module stuff.

I would like to have it reviewed asap, as I have ready next pull with simple Item Filter editor I'd like to use in Prophecy league :p

The reasons why I didn't make DLLs out of them:
1. ability to hot-fix and improve stuff, simply full  control over code
2. not fan of having lot of tiny DLLs for each 3-5 source files and having CLR to link them all on each launch. We have like 180+ files in project, that's 36 DLLs/subprojects for each 5 files :p

I'm not against using DLL isolation for our app. Actually I'd like to have some UI and other larger logical chunks separated, but there should be line, which goes into DLL and which don't.

"Contrib" folder is common mechanism from old GNU days. It was used for years, and still being used. Just have to include README, LICENCE and other files required by licence of contributed piece of work.

**Comment by brather1ng** [comment]
I'm fine with having the submodule files in a subfolder. DLLs were just my first idea and I thought it were more files.

This unit test is running on my pull request branch so it shouldn't be "disabled" like this for long.

**Comment by EmmittJ** [comment]
Hmm, I made a release a couple days ago, so unless something broke the unit
tests were all working

**Comment by l0g0sys** [comment]
It's not disabled, it just always passes, as it doesn't have data to 
compare now.

I wrote down wrong comment. I didn't touch TestCharacterSheet class at 
all. Just commented out lines in test data (Build.xml).

The test was failing for me, didn't do proper investigation, but my 
guess was that tree URL in Build.xml didn't work with current tree.

Doesn't really matter.

Rather be safe than sorry when you gonna do release with new tree.

**Comment by l0g0sys** [comment]
So now please focus on submodule part :)

**Comment by brather1ng** [comment]
The themes for WpfRangeControls are not applied (open the Equipment tab, there is no scroll bar). This is probably a mix of `Themes/Generic.xaml` not being in the project root and these styles partially being overwritten in our resources. The best solution would be to put WpfRangeControls into its own project.

**Comment by l0g0sys** [comment]
Thanks, missed that.

Styles are not applied automatically, you have to reference them in XAML 
directly or make them compile into application resources.

No need for project to apply styles.  So best solution is to add 1 line 
to App.xaml.

**Comment by brather1ng** [comment]
> Styles are not applied automatically, you have to reference them in XAML directly or make them compile into application resources.

That's not true, styles located in `Themes/Generic.xaml` are applied automatically. That file is generally used for default styles of new controls, like in this case. That's why it would work if it's in its own project. However, what you did seems to work either, so I don't mind.

**Comment by l0g0sys** [comment]
Well, the only reason they were applied before, was thanks to ThemeInfo 
attribute set to ResourceDictionaryLocation.SourceAssembly for its assembly.

So, ok i missed out the third method, and that's direct compilation into 
assembly using ThemeInfo attribute.

Still, nothing automatic here :)

**Comment by l0g0sys** [comment]
Is ok to merge it now?

**Comment by brather1ng** [comment]
Looks good to me. Don't know if anyone else wants to look over it.

**Comment by l0g0sys** [comment]
Well, endorsement from you is enough ;)
Only that XAML styling stuff was real issue, and that was fixed.

**Pull request merged**
