### PR TITLE
Skill tree generator - first set of features

### PR DESCRIPTION
**Pull request by brather1ng**
The skill tree generator implementation (see #106) is now at a point where it has enough features to be worth including in the program in my opinion.

### New features

The user can input basic attributes ('#% increased maximum Life', '#% increased Attack Speed with Bows', everything that appears on skill nodes) and pseudo attributes (where the basic attributes are simply added together given settings for weapon class, tags and off hand style, like '#% increased (total) Physical Damage') as constraints with a target value and a weight for which the program tries to find the optimal tree with respect to those constraints and a given number of points available. What is not yet implemented are constraints that include the gear in any shape or form and an automated solver that derives the constraints in some kind of heuristical way.

### UI overview

You can finde the generator under the menu at "Tools -> Nodes -> Skill Tree Generator". In the window are some general settings and a tab for every different solver. "Advanced" contains the new functionality, "Automated" does nothing atm and "Tagged Nodes" is exactly the "Skill Tagged Nodes" feature (which is multiple times faster now), included there for testing purposes.

In the "Advanced" tab, "Attributes" is for the raw attributes, "Pseudo Attributes" is for combined raw attributes, "Combined Attributes" will later be for stuff including the gear and "Settings" contains settings related to which raw attributes are calculated into pseudo attributes atm. One thing worth pointing out is that keystones will only be included in solutions if they are check-tagged (so if you check Phase Acro but not Acro and click "Run", it will give you an error because the tree is disconnected).

If you think this is in a pull worthy state, I'll remove the things that don't do anything from the UI for the pull.

### "Optimize existing tree" use case

You can optimize an existing tree as follows:

1. Skill your tree in the general UI.
2. Open the skill tree generator window and make sure total points equals the number of skilled nodes (if you start it after skilling the tree and it is the first start, it should do that automatically, if not, change additional points until total points are correct or click "Reset").
4. Switch to "Advanced" -> "Settings" and select weapon class, off hand and tags fitting your build and main skill.
5. Switch to "Attributes", click "Load from tree" and then "Convert to pseudo attributes".
6. Remove attribute constraints that are unimportant for you.
7. Switch to "Pseudo Attributes" and remove constraints that are unimportant for you.
8. Make sure the automatically check-tagged nodes are only nodes you feel must be included in any case (like keystones and important notables).
9. Optionally check the "current tree as initial solution" check box. If similar trees are better, this will generally produce better results. If the tree needs to change heavily, it will generally produce worse results. If you keep it unchecked, make sure to reset the skill tree.
10. Click "Run" and wait.

Do note that trees are very specific, so if it is already an acceptable tree, it probably won't get any better outside of pathing between nodes for which "Skill Tagged Nodes" is suited much better.

### Pseudo attributes in the general planner

Since the support for pseudo attributes was already requested for the general tree planner (see #185) and my implementation would easily support it, I'd work on that before implementing the missing generator features if others find it useful.

My implementation loads the definitions of pseudo attributes with contained attributes and their conditions from xml files and evaluates if attributes are calculated into the pseudo attribute based on those conditions. See the [Data/PseudoAttributes](https://github.com/brather1ng/PoESkillTree/tree/treeGen/WPFSKillTree/Data/PseudoAttributes) folder for the xml files and the [TreeGenerator/Model/PseudoAttributes](https://github.com/brather1ng/PoESkillTree/tree/treeGen/WPFSKillTree/TreeGenerator/Model/PseudoAttributes) folder for the implementation.

### Screenshots

Attributes Tab
Pseudo Attributes Tab
Settings Tab

If you like to have a download link to the compiled program for trying it out, I'll try to get that up.

### CODE REVIEW

**Comment by EmmittJ** [comment]
This looks really good! I did some testing on a couple builds, and it seems to work like a charm. I haven't found any bugs yet. Can everyone else pull this and mess around with it? @l0g0sys @SpaceOgre

**Comment by MLanghof** [comment]
Currently, clicking "Reset" in the settings view deletes all the attributes in the list as expected, but it doesn't re-add them to the pool of mods you can choose to add. For example: http://i.imgur.com/3okNph3.png

**Comment by brather1ng** [comment]
Fixed that and another bug related to it.

Thanks! Yes, it feels way better than what we had at first. I don't understand why datagrids are so unintuitive to use out of the box.

**Comment by EmmittJ** [comment]
So been messing around with this and maybe I missed something, but why is the 'Automated' tab unable to be clicked lol

**Comment by EmmittJ** [comment]
If you would like to remove the unused ui elements I will pull this a we can throw up a new release

**Comment by brather1ng** [comment]
Unused/confusing stuff is removed from the UI now.

I am not sure whether having the 'Tagged Nodes' tab there is useful. It was useful for debugging but if you think it creates more confusion than it helps, I can remove that one as well.

**Comment by EmmittJ** [comment]
Maybe remove/comment it out for now. It seems as though it should be too hard to actually implement that feature entirely into this UI (which is a good idea).

**Comment by brather1ng** [comment]
Moving it entirely to the new UI sounds good. The code is implemented with the new stuff anyway, its just the old menu entry I kept.

I'll probably disable the useless settings when the 'Tagged Nodes' tab is selected and throw some explanation into that tab and then remove the old menu entry. But that is something for later, so I'll just comment it out for now.

**Comment by EmmittJ** [comment]
I like that idea. Thank you for your hard work! This is seriously cool. Do you mind if I use your pull request description in the wiki section for the general public to learn how to use it?

**Comment by brather1ng** [comment]
No problem, was fun to do this :)
Nope, feel free to use it.

**Comment by EmmittJ** [comment]
Ah, something I just realized, so when running the test 'DijkstraUnconnected ' the test case fails do to no GraphNotConnectException.

**Comment by brather1ng** [comment]
I did run those tests at some point ...
Probably changed something so it gets thrown at a different point. I'll look into it in a few minutes.

**Comment by EmmittJ** [comment]
Sweet, thanks! I don't exactly what to mess with that stuff since I don't exactly have knowledge of the system as a whole.

**Pull request merged**
