### PR TITLE
Downgraded to .Net 4.0 for compatibilty with other operating systems

### PR DESCRIPTION
**Pull request by EmmittJ**
Updated Test Build to reflect Mana Per Level Changes
Updated packages to match
Fixed misc. errors that were caused by downgrade

This is a suggested fix for #226. I need everyone to build and run this on their systems to make sure there aren't any compatibility issues. 
@SpaceOgre @l0g0sys @brather1ng @MLanghof

### CODE REVIEW

**Comment by brather1ng** [comment]
Everything seems to work fine for me (Win 10, VS 2015).
All async-using features and the settings stuff worked for what I tried.

**Comment by EmmittJ** [comment]
I am on Win 10, VS 2012 just to add my specs

**Comment by l0g0sys** [comment]
Work's on Win7, .Net 4.5.2 running with CLR v4.0.30319.
Though, for some reason menus are aligned with top-right corner instead of top-left. It looks really awkward.
menu-alignment-bug

**Comment by EmmittJ** [comment]
Hmm, I am not having that issue.

**Comment by EmmittJ** [comment]
Whoops, I am using VS 2013 Update 2, wasn't at comp to actually check what I was using.

**Comment by SpaceOgre** [comment]
Sadly I will not have access to my computer for a few more days so won't be able to test. One thing though, I think it would be good to test run this on Linux before we commit to the downgrade, since the new packages might not work correctly.

**Comment by EmmittJ** [comment]
I agree. I don't exactly have a Linux box set up, but I might be able to
get one running.

**Comment by EmmittJ** [comment]
So, after running [this] (https://support.microsoft.com/en-us/kb/2468871) (KB2468871) I was able to run this successfully on Windows XP. I am not sure we can guarantee Linux support, but we can at least get people on XP back to using an updated skilltree.

**Comment by EmmittJ** [comment]
Would you guys be cool if I pulled this?

**Comment by SpaceOgre** [comment]
To be honest I don't feel like windows xp is a good enough reason for this
change. An OS that is no longer supported by its manufacturer shouldn't
really impact a new app.

**Comment by EmmittJ** [comment]
True, but the thing is there are a lot of people that continue to pm about it. If WINE was updated this would be nice

**Comment by EmmittJ** [comment]
I would agree though that it would make sense not to support it.

**Comment by brather1ng** [comment]
If XP support is the only thing this would provide it doesn't make much sense to pull it imo.

Downgrading to .net 4.0 because many people can't upgrade their .net framework on the pc they want to use the app would be a valid reason. But I don't know how many people are affected by that.

**Comment by EmmittJ** [comment]
That is another reason. I am not sure what our demographic is because
Github doesn't provide those stats, but I have a lot of people requesting
4.0 because they can't use it at work on 4.5 haha

**Comment by EmmittJ** [comment]
I will close the pull request, but I will keep the branch up if someone thinks they can work on it.

**Pull request closed without merging**
