### PR TITLE
Multiple smaller changes (LoadingWindow text, saving window position, asynchronous tasks)

### PR DESCRIPTION
**Pull request by brather1ng**
Fixed some smaller issues:
- #194: LoadingWindow has the info text as a property that can be set over StartLoadingWindow.
- #174: Mahapps has a property `SaveWindowPosition` that does all the work.
- Added a clear button for the search text field (a property from Mahapps I stumbled upon, seems useful in this case).
- #150: Running background tasks are shown in the title bar. Implemented checking for updates and resolving poeurl/tinyurl links as such tasks. Below is a screenshot of how it looks, do you guys think that is a proper way of showing that work is happening?
asynctasks  
Also, is there any particular reason the app doesn't use .net4.5? Because the async/await stuff would make this a lot easier to implement.

### CODE REVIEW

**Comment by EmmittJ** [comment]
I am pretty sure at some point this project was in .net 4.5, but I am not sure what happened there. 

Anyway this looks really nicely handled for the background stuff

**Comment by SpaceOgre** [comment]
I don't think there should be any problems with going for .net 4.5.
And I agree with @EmmittJ that the background solution is really nice.

About the ```SaveWindowPosition``` from what I can tell it will store this in AppData somewhere, which is fine but if you have the program installed as portal it might not be so nice. But that is up for discussion of course.

**Comment by l0g0sys** [comment]
So maybe using Registry for storing UI state?

**Comment by brather1ng** [comment]
>About the SaveWindowPosition from what I can tell it will store this in AppData somewhere, which is fine but if you have the program installed as portal it might not be so nice. But that is up for discussion of course.

Yes, it stores the user.config in AppData by default. For portable it should probably store it in the program folder (so Registry wouldn't be better imo).
I'll try to produce an installer and check where it saves it with a portable installation later. Maybe it already does it correctly, else I'd need to find a way to modify the user.config save path or a completely different way of storing the UI state.

**Comment by SpaceOgre** [comment]
Yes, storing it in program folder for portable would be best.

**Comment by brather1ng** [comment]
This is done now (they are saved in AppData.GetFolder("Settings"), but needed an update of MahApps.Metro.
I also upgraded to .Net 4.5 to use async/await for the background task stuff.

So the commit contains a ton of changes, the relevant changes are in Settings.cs, CustomSettingsProvider.cs and MainWindow.xaml.cs.

I'll try to find out if the upgrade has broken anything later.

**Pull request merged**
