### PR TITLE
UpdateUI & CurrentClass Functions

### PR DESCRIPTION
**Pull request by EmmittJ**
UpdateUI is now a function and should be the one called when updating UI elements. Let me know if I missed a function

You can now get the current class from a loaded tree

### CODE REVIEW

**Comment by EmmittJ** [comment]
What do you guys think @l0g0sys @SpaceOgre

**Comment by l0g0sys** [comment]
Yep, makes more sense than UpdateAttributeList() :)

**Comment by SpaceOgre** [comment]
I have not been at a computer all day but from what I see from the phone it
looks way better :)

**Comment by EmmittJ** [comment]
Alright, I will merge it then!

**Comment by SpaceOgre** [comment]
Not sure if completely correct line but around 1270 in main there is an unessesary setting of current class, since the call to UpdateUI comes right after.

**Comment by EmmittJ** [comment]
Removed it.

**Comment by SpaceOgre** [comment]
Oh and why do we need CurrentClass(), is not Tree.Chartype enough? Just asking, hard to get a good look on the phone :)

**Comment by EmmittJ** [comment]
I actually just was looking at that and felt stupid lol It isn't needed either.

**Pull request merged**
